variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:linux:
  stage: build
  tags:
    - cad1
    - shell
  script:
    - export GOPATH=~/go/
    - export PATH=/usr/lib/llvm-5.0/bin:/usr/local/go/bin:${GOPATH}/bin:${PATH}
    - cd ~/go/src/Genesis
    - git pull origin master
    - git pull --tags
    - git submodule update
    - ./build.sh
  cache:
    untracked: true
  artifacts:
    paths:
      - genesis/
  except:
    - /^feature\/wip-.*/

test:linux:
  stage: test
  tags:
    - cad1
    - shell
  script:
    - export HALIDE_ROOT=~/go/src/Genesis/genesis/
    - ./testall.sh
  dependencies:
    - build:linux
  except:
    - /^feature\/wip-.*/
